name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        run: |
          docker run \
            -e GITHUB_USER_NAME=Rohitsunnyy \
            -e OUTPUT_PATH=dist/github-contribution-grid-snake.svg \
            platane/snk

      - name: List files in the repository (debugging)
        run: ls -R

      - name: Commit and push the Snake animation to the repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main --rebase
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/github-contribution-grid-snake.svg
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generated Snake animation" || echo "No changes to commit"
          git push
